
CREATE WAREHOUSE IF NOT EXISTS PHISHING_ML_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for Phishing Email ML Pipeline';

USE WAREHOUSE PHISHING_ML_WH;

CREATE DATABASE IF NOT EXISTS PHISHING_DB
  COMMENT = 'Database for Phishing Email Detection Project';

USE DATABASE PHISHING_DB;

CREATE SCHEMA IF NOT EXISTS PHISHING_SCHEMA
  COMMENT = 'Schema for all phishing ML pipeline objects';

USE SCHEMA PHISHING_SCHEMA;

DROP TABLE IF EXISTS RAW_EMAILS;

CREATE OR REPLACE TABLE RAW_EMAILS (
    EMAIL_ID          INTEGER,
    SENDER            VARCHAR(200),
    SENDER_DOMAIN     VARCHAR(200),
    SUBJECT           VARCHAR(500),
    BODY              TEXT,
    HAS_URL           INTEGER,         -- 1 = has URL, 0 = no URL
    URL_COUNT         INTEGER,         -- Number of URLs in email
    HAS_IP_URL        INTEGER,         -- 1 = URL contains IP address
    URL_LENGTH        INTEGER,         -- Average URL length
    HAS_URGENT_WORDS  INTEGER,         -- 1 = contains urgency keywords
    HTML_TAGS_COUNT   INTEGER,         -- Number of HTML tags
    NUM_SPECIAL_CHARS INTEGER,         -- Count of special characters
    WORD_COUNT        INTEGER,         -- Total word count in body
    SUBJECT_LENGTH    INTEGER,         -- Character length of subject
    SENDER_NAME_MISMATCH INTEGER,      -- 1 = display name != domain
    HAS_ATTACHMENT    INTEGER,         -- 1 = has attachment
    REPLY_TO_DIFFERENT INTEGER,        -- 1 = reply-to != sender
    SPF_PASS          INTEGER,         -- 1 = SPF authentication passed
    DKIM_PASS         INTEGER,         -- 1 = DKIM authentication passed
    LABEL             INTEGER          -- 1 = Phishing, 0 = Legitimate
);

CREATE OR REPLACE STAGE PHISHING_DATA_STAGE
    FILE_FORMAT = (
        TYPE = 'CSV'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        SKIP_HEADER = 1
        NULL_IF = ('NULL', 'null', '')
    )
    COMMENT = 'Stage for uploading phishing email CSV data';

COPY INTO RAW_EMAILS
FROM @PHISHING_DATA_STAGE/phishing_emails_sample.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS TOTAL_RECORDS FROM RAW_EMAILS;
SELECT * FROM RAW_EMAILS LIMIT 5;

SELECT
    SUM(CASE WHEN EMAIL_ID IS NULL THEN 1 ELSE 0 END)            AS NULL_EMAIL_ID,
    SUM(CASE WHEN SENDER IS NULL THEN 1 ELSE 0 END)              AS NULL_SENDER,
    SUM(CASE WHEN LABEL IS NULL THEN 1 ELSE 0 END)               AS NULL_LABEL,
    SUM(CASE WHEN WORD_COUNT IS NULL THEN 1 ELSE 0 END)          AS NULL_WORD_COUNT,
    SUM(CASE WHEN HAS_URL IS NULL THEN 1 ELSE 0 END)             AS NULL_HAS_URL
FROM RAW_EMAILS;

SELECT
    LABEL,
    CASE WHEN LABEL = 1 THEN 'Phishing' ELSE 'Legitimate' END AS EMAIL_TYPE,
    COUNT(*) AS COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM RAW_EMAILS
GROUP BY LABEL
ORDER BY LABEL DESC;

SELECT
    CASE WHEN LABEL = 1 THEN 'Phishing' ELSE 'Legitimate' END AS EMAIL_TYPE,
    ROUND(AVG(URL_COUNT), 2)            AS AVG_URL_COUNT,
    ROUND(AVG(URL_LENGTH), 2)           AS AVG_URL_LENGTH,
    ROUND(AVG(WORD_COUNT), 2)           AS AVG_WORD_COUNT,
    ROUND(AVG(HTML_TAGS_COUNT), 2)      AS AVG_HTML_TAGS,
    ROUND(AVG(NUM_SPECIAL_CHARS), 2)    AS AVG_SPECIAL_CHARS,
    ROUND(AVG(SUBJECT_LENGTH), 2)       AS AVG_SUBJECT_LENGTH
FROM RAW_EMAILS
GROUP BY LABEL
ORDER BY LABEL DESC;

SELECT
    CASE WHEN LABEL = 1 THEN 'Phishing' ELSE 'Legitimate' END AS EMAIL_TYPE,
    ROUND(AVG(HAS_URL) * 100, 1)              AS PCT_HAS_URL,
    ROUND(AVG(HAS_IP_URL) * 100, 1)           AS PCT_HAS_IP_URL,
    ROUND(AVG(HAS_URGENT_WORDS) * 100, 1)     AS PCT_HAS_URGENT,
    ROUND(AVG(SENDER_NAME_MISMATCH) * 100, 1) AS PCT_NAME_MISMATCH,
    ROUND(AVG(REPLY_TO_DIFFERENT) * 100, 1)   AS PCT_REPLY_DIFF,
    ROUND(AVG(SPF_PASS) * 100, 1)             AS PCT_SPF_PASS,
    ROUND(AVG(DKIM_PASS) * 100, 1)            AS PCT_DKIM_PASS
FROM RAW_EMAILS
GROUP BY LABEL
ORDER BY LABEL DESC;

SELECT
    SPLIT_PART(SENDER_DOMAIN, '.', -1)  AS TLD,
    COUNT(*)                             AS COUNT,
    ROUND(SUM(LABEL) * 100.0 / COUNT(*), 1) AS PHISHING_RATE_PCT
FROM RAW_EMAILS
GROUP BY TLD
ORDER BY COUNT DESC
LIMIT 15;

CREATE OR REPLACE TABLE ENGINEERED_FEATURES AS
SELECT
    EMAIL_ID,
    HAS_URL,
    URL_COUNT,
    HAS_IP_URL,
    URL_LENGTH,
    HAS_URGENT_WORDS,
    HTML_TAGS_COUNT,
    NUM_SPECIAL_CHARS,
    WORD_COUNT,
    SUBJECT_LENGTH,
    SENDER_NAME_MISMATCH,
    HAS_ATTACHMENT,
    REPLY_TO_DIFFERENT,
    SPF_PASS,
    DKIM_PASS,

    CASE WHEN SPF_PASS = 0 AND DKIM_PASS = 0 THEN 1 ELSE 0 END AS AUTH_BOTH_FAILED,

    CASE WHEN WORD_COUNT > 0 THEN ROUND(URL_COUNT * 1.0 / WORD_COUNT, 4) ELSE 0 END AS URL_DENSITY,

    CASE WHEN WORD_COUNT > 0 THEN ROUND(NUM_SPECIAL_CHARS * 1.0 / WORD_COUNT, 4) ELSE 0 END AS SPECIAL_CHAR_RATIO,

    CASE WHEN HAS_URGENT_WORDS = 1 AND SENDER_NAME_MISMATCH = 1
              AND (SPF_PASS = 0 OR DKIM_PASS = 0) THEN 1 ELSE 0 END AS HIGH_RISK_COMBO,

    CASE WHEN URL_LENGTH > 75 THEN 1 ELSE 0 END AS HAS_LONG_URL,

    CASE WHEN WORD_COUNT < 20 THEN 1 ELSE 0 END AS SHORT_BODY,

    LABEL
FROM RAW_EMAILS;

SELECT * FROM ENGINEERED_FEATURES LIMIT 5;

CREATE OR REPLACE VIEW TRAIN_DATA AS
SELECT * FROM ENGINEERED_FEATURES
WHERE MOD(EMAIL_ID, 5) != 0;   -- ~80% training (rows where id not divisible by 5)

CREATE OR REPLACE VIEW TEST_DATA AS
SELECT * FROM ENGINEERED_FEATURES
WHERE MOD(EMAIL_ID, 5) = 0;    -- ~20% test (rows where id divisible by 5)

SELECT 'TRAIN' AS SPLIT, COUNT(*) AS RECORD_COUNT FROM TRAIN_DATA
UNION ALL
SELECT 'TEST', COUNT(*) FROM TEST_DATA;

CREATE OR REPLACE TABLE MODEL_PREDICTIONS (
    EMAIL_ID          INTEGER,
    ACTUAL_LABEL      INTEGER,
    PREDICTED_LABEL   INTEGER,
    PREDICTION_PROBA  FLOAT,
    IS_CORRECT        BOOLEAN,
    SPLIT_TYPE        VARCHAR(10)   -- 'TEST' or 'TRAIN'
);

CREATE OR REPLACE TABLE MODEL_METRICS (
    MODEL_NAME        VARCHAR(100),
    ACCURACY          FLOAT,
    PRECISION_SCORE   FLOAT,
    RECALL_SCORE      FLOAT,
    F1_SCORE          FLOAT,
    AUC_ROC           FLOAT,
    TRAINED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW MODEL_EVAL_SUMMARY AS
SELECT
    MODEL_NAME,
    ROUND(ACCURACY * 100, 2)       AS ACCURACY_PCT,
    ROUND(PRECISION_SCORE * 100, 2) AS PRECISION_PCT,
    ROUND(RECALL_SCORE * 100, 2)   AS RECALL_PCT,
    ROUND(F1_SCORE * 100, 2)       AS F1_PCT,
    ROUND(AUC_ROC, 4)              AS AUC_ROC,
    TRAINED_AT
FROM MODEL_METRICS
ORDER BY F1_SCORE DESC;

CREATE OR REPLACE VIEW CONFUSION_MATRIX AS
SELECT
    ACTUAL_LABEL,
    PREDICTED_LABEL,
    COUNT(*) AS COUNT,
    CASE
        WHEN ACTUAL_LABEL = 1 AND PREDICTED_LABEL = 1 THEN 'True Positive (TP)'
        WHEN ACTUAL_LABEL = 0 AND PREDICTED_LABEL = 0 THEN 'True Negative (TN)'
        WHEN ACTUAL_LABEL = 1 AND PREDICTED_LABEL = 0 THEN 'False Negative (FN)'
        WHEN ACTUAL_LABEL = 0 AND PREDICTED_LABEL = 1 THEN 'False Positive (FP)'
    END AS CLASSIFICATION_TYPE
FROM MODEL_PREDICTIONS
WHERE SPLIT_TYPE = 'TEST'
GROUP BY ACTUAL_LABEL, PREDICTED_LABEL
ORDER BY ACTUAL_LABEL DESC, PREDICTED_LABEL DESC;
